### PR TITLE
adding 2 branches and files

### PR DESCRIPTION
**Pull request by Favourhub22**
Kindly approve request

### CODE REVIEW

**Review by Yoannoay — APPROVED** [review]
Nice puns !!

**Review by Yoannoay — APPROVED** [review]
Good stuff

**Review by Yoannoay — APPROVED** [review]

**Review by su-adam — APPROVED** [review]

**Review by su-adam — APPROVED** [review]
Looks good

**Review by Favourhub22 — COMMENTED** [review]
Reviewed

**Review by Favourhub22 — COMMENTED** [review]
Review

**Review by su-adam — APPROVED** [review]
Looks good!

**Review by ThakkarPurvi — APPROVED** [review]
Awesome

**Review by Yoannoay — APPROVED** [review]

**Pull request merged**
